// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// Example is the golang structure for table sys_example.
type Example internal.Example

// Fill with you ideas below.