// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// MemberLevel is the golang structure for table ums_member_level.
type MemberLevel internal.MemberLevel

// Fill with you ideas below.