// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"easygoadmin/app/model/internal"
)

// Member is the golang structure for table ums_member.
type Member internal.Member

// Fill with you ideas below.