// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal



// UserRole is the golang structure for table sys_user_role.
type UserRole struct {
    UserId uint `orm:"user_id" json:"userId"` // 人员ID  
    RoleId uint `orm:"role_id" json:"roleId"` // 角色ID  
}